name: example-webpack
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  wait:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress tests
        uses: ./
        with:
          working-directory: src/index
          start: npm start
          wait-on: 'http://localhost:8080'
